name = "archerfilmstudios-homepage"
main = "workers/src/index.js"
compatibility_date = "2026-01-01"

[assets]
directory = "./dist"
run_worker_first = ["/api/*", "/avatars/*", "/posters/*"]

[[d1_databases]]
binding = "DB"
database_name = "archer-club"
database_id = "fba0b17b-6b13-4197-92f9-ce4885491e0b"

[[r2_buckets]]
binding = "AVATARS"
bucket_name = "avatars"
